name: Build & Publish Release APK

on:
  push:
    branches: ["apk-cd"]

jobs:
  build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
        - name: Checkout source
          uses: actions/checkout@v3

        - name: Setup java
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16.x
        - run: npm i
        - name: Build
          run: npm run build
        - name: Capacitor sync
          run: npx cap sync --preserveProjectNodeModules=true
        - name: checkout code
          uses: actions/checkout@v2
        - name: Make Gradle executable
          run: chmod +x ./android/gradlew
        - name: Build Release APK
          run: ./android/gradlew -p ./android assembleRelease
        - name: Releasing using Hub
          uses: kyze8439690/action-release-releaseapk@master
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            APP_FOLDER: ./android/app